spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '1234'
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

delivery: "http://delivery-service:8080"
catalog: "http://catalog-service:8080"
payment: "http://payment-service:8080"